### ISSUE TITLE
Production Readiness Checklist

### ISSUE THREAD

**Issue by shachar-langer** [morehumaninternet/roar-server#17]
The [server](http://roar-server.herokuapp.com/docs.html) runs on Heroku. We need to:
- [ ] Deploy the latest code.
- [ ] Migrate the database (carefully!).
- [ ] Do a test run.
