### ISSUE TITLE
Log redis and postgres errors to sentry

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-server#18]
## Context

Redis or postgres may fail, and we want to know about it

## Todo

- [ ] write errors to sentry when redis fails
- [ ] write errors to sentry when postgres fails
- [ ] temporarily turn off these services in heroku to test that the alerts work
